/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { useLoader } from "@react-three/fiber";
import { MaterialProperties } from "three";

type GLTFResult = GLTF & {
  nodes: {
    BookMesh002: THREE.Mesh;
    BookMesh002_1: THREE.Mesh;
  };
  materials: {
    Template_152x229: THREE.MeshStandardMaterial;
    "Pages.001": THREE.MeshPhysicalMaterial;
  };
};

export function BookXL(
  props: React.JSX.IntrinsicElements["group"] & {
    bookTexture?: string;
    materialControls: Partial<MaterialProperties>;
  }
) {
  const { nodes, materials } = useGLTF(
    "/models/BookXL.glb"
  ) as unknown as GLTFResult;

  const texture = useLoader(
    THREE.TextureLoader,
    props.bookTexture || "/models/textures/template-combined-xl.jpg"
  );
  texture.flipY = false;
  texture.colorSpace = THREE.SRGBColorSpace;
  texture.anisotropy = 8;

  const roughnessMap = useLoader(
    THREE.TextureLoader,
    "/models/textures/roughness_map.jpg"
  );

  return (
    <group {...props} dispose={null}>
      <group rotation-y={Math.PI / 2}>
        <mesh
          name="BookMeshXL"
          castShadow
          receiveShadow
          geometry={nodes.BookMesh002.geometry}
        >
          <meshStandardMaterial
            map={texture}
            roughnessMap={roughnessMap}
            toneMapped
            {...props.materialControls}
          />
        </mesh>
        <mesh
          name="BookMesh002_1"
          receiveShadow
          geometry={nodes.BookMesh002_1.geometry}
          material={materials["Pages.001"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/models/BookXL.glb");
