/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useEffect, useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { useFrame, useLoader } from "@react-three/fiber";
import { MeshStandardMaterialProperties } from "three";
import { lerp } from "three/src/math/MathUtils.js";
import { useSnapshot } from "valtio";
import { bookStore } from "@/app/store/bookStore";
import { Book } from "@/types/app";

type GLTFResult = GLTF & {
  nodes: {
    BookMesh002: THREE.Mesh;
    BookMesh002_1: THREE.Mesh;
  };
  materials: {
    Template_152x229: THREE.MeshStandardMaterial;
    "Pages.001": THREE.MeshPhysicalMaterial;
  };
};

export function BookXL(
  props: React.JSX.IntrinsicElements["group"] & {
    book: Book;
    materialControls: Partial<MeshStandardMaterialProperties>;
  }
) {
  const { nodes, materials } = useGLTF(
    "/models/BookXL.glb"
  ) as unknown as GLTFResult;

  const texture = useLoader(
    THREE.TextureLoader,
    props.book.bookTexture || "/models/textures/template-combined-xl.jpg"
  );
  texture.flipY = false;
  texture.colorSpace = THREE.SRGBColorSpace;
  texture.anisotropy = 8;

  const roughnessMap = useLoader(
    THREE.TextureLoader,
    "/models/textures/roughness_map.jpg"
  );

  // Opacity animation
  const { focusedBookId } = useSnapshot(bookStore);
  const isHidden = focusedBookId !== null && focusedBookId !== props.book.id;
  const ref = useRef<THREE.Group>(null);
  const meshMaterials: THREE.Object3D[] = [];
  const delayFrames = useRef(0);
  const frameCount = useRef(0);

  useEffect(() => {
    frameCount.current = 0;
    delayFrames.current = isHidden ? 25 : 0;
  }, [isHidden]);

  useFrame(() => {
    ref.current?.getObjectsByProperty("type", "Mesh", meshMaterials);
    meshMaterials.forEach((mesh) => {
      const material = (mesh as unknown as THREE.Mesh)
        .material as THREE.MeshStandardMaterial;
      material.transparent = true;
      if (frameCount.current < delayFrames.current) {
        frameCount.current++;
      } else {
        material.opacity = lerp(material.opacity, isHidden ? 0 : 1, 0.5);
      }
    });
    meshMaterials.length = 0;
  });

  return (
    <group {...props} dispose={null}>
      <group rotation-y={Math.PI / 2} ref={ref}>
        <mesh
          name="BookMeshXL"
          castShadow
          receiveShadow
          geometry={nodes.BookMesh002.geometry}
        >
          <meshStandardMaterial
            map={texture}
            roughnessMap={roughnessMap}
            toneMapped
            {...props.materialControls}
          />
        </mesh>
        <mesh
          name="BookMesh002_1"
          castShadow
          receiveShadow
          geometry={nodes.BookMesh002_1.geometry}
        >
          <meshStandardMaterial
            {...materials["Pages.001"]}
            {...props.materialControls}
          />
        </mesh>
      </group>
    </group>
  );
}

useGLTF.preload("/models/BookXL.glb");
