/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { useBookTextures } from "@/app/hooks/useBookTextures";

type GLTFResult = GLTF & {
  nodes: {
    BookMesh: THREE.Mesh;
    BookMesh_1: THREE.Mesh;
    BookMesh_2: THREE.Mesh;
    BookMesh_3: THREE.Mesh;
  };
  materials: {
    Front_127x203: THREE.MeshStandardMaterial;
    Pages: THREE.MeshPhysicalMaterial;
    Back_127x203: THREE.MeshStandardMaterial;
    Side_127x203: THREE.MeshStandardMaterial;
  };
};

export function BookSM(
  props: React.JSX.IntrinsicElements["group"] & {
    textures: { front: string; side: string };
  }
) {
  const { nodes, materials } = useGLTF(
    "/models/Book_SM.gltf"
  ) as unknown as GLTFResult;

  // Load and configure textures using the reusable hook
  useBookTextures(props.textures, materials, {
    front: "Front_127x203",
    side: "Side_127x203",
    back: "Back_127x203"
  });

  return (
    <group {...props} dispose={null}>
      <group rotation-y={Math.PI / 2}>
        <mesh
          name="BookMesh"
          castShadow
          receiveShadow
          geometry={nodes.BookMesh.geometry}
          material={materials.Front_127x203}
        />
        <mesh
          name="BookMesh_1"
          castShadow
          receiveShadow
          geometry={nodes.BookMesh_1.geometry}
          material={materials.Pages}
        />
        <mesh
          name="BookMesh_2"
          castShadow
          receiveShadow
          geometry={nodes.BookMesh_2.geometry}
          material={materials.Back_127x203}
        />
        <mesh
          name="BookMesh_3"
          castShadow
          receiveShadow
          geometry={nodes.BookMesh_3.geometry}
          material={materials.Side_127x203}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/models/Book_SM.gltf");
