/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useMemo, useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { useBookTextures } from "@/app/hooks/useBookTextures";

type GLTFResult = GLTF & {
  nodes: {
    BookMesh004: THREE.Mesh;
    BookMesh004_1: THREE.Mesh;
    BookMesh004_2: THREE.Mesh;
    BookMesh004_3: THREE.Mesh;
  };
  materials: {
    Front_152x229: THREE.MeshStandardMaterial;
    Pages: THREE.MeshPhysicalMaterial;
    Back_152x229: THREE.MeshStandardMaterial;
    Side_152x229: THREE.MeshStandardMaterial;
  };
};

export function BookXL(
  props: React.JSX.IntrinsicElements["group"] & {
    textures: { front: string; side: string };
  }
) {
  const { nodes, materials } = useGLTF(
    "/models/Book_XL.gltf"
  ) as unknown as GLTFResult;

  // Load and configure textures using the reusable hook
  useBookTextures(props.textures, materials, {
    front: "Front_152x229",
    side: "Side_152x229",
    back: "Back_152x229" // Optional: also apply front texture to back
  });

  return (
    <group {...props} dispose={null}>
      <group rotation-y={Math.PI / 2}>
        <mesh
          name="BookMesh004"
          castShadow
          receiveShadow
          geometry={nodes.BookMesh004.geometry}
          material={materials.Front_152x229}
        />
        <mesh
          name="BookMesh004_1"
          castShadow
          receiveShadow
          geometry={nodes.BookMesh004_1.geometry}
          material={materials.Pages}
        />
        <mesh
          name="BookMesh004_2"
          castShadow
          receiveShadow
          geometry={nodes.BookMesh004_2.geometry}
          material={materials.Back_152x229}
        />
        <mesh
          name="BookMesh004_3"
          castShadow
          receiveShadow
          geometry={nodes.BookMesh004_3.geometry}
          material={materials.Side_152x229}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/models/Book_XL.gltf");
