/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    BookMesh005: THREE.Mesh;
    BookMesh005_1: THREE.Mesh;
    BookMesh005_2: THREE.Mesh;
    BookMesh005_3: THREE.Mesh;
  };
  materials: {
    Front_108x175: THREE.MeshStandardMaterial;
    Pages: THREE.MeshPhysicalMaterial;
    Back_108x175: THREE.MeshStandardMaterial;
    Side_108x175: THREE.MeshStandardMaterial;
  };
};

export function BookXS(props: React.JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/models/Book_XS.gltf"
  ) as unknown as GLTFResult;
  
  return (
    <group {...props} dispose={null}>
      <group rotation-y={Math.PI / 2}>
        <mesh
          name="BookMesh005"
          castShadow
          receiveShadow
          geometry={nodes.BookMesh005.geometry}
          material={materials.Front_108x175}
        />
        <mesh
          name="BookMesh005_1"
          castShadow
          receiveShadow
          geometry={nodes.BookMesh005_1.geometry}
          material={materials.Pages}
        />
        <mesh
          name="BookMesh005_2"
          castShadow
          receiveShadow
          geometry={nodes.BookMesh005_2.geometry}
          material={materials.Back_108x175}
        />
        <mesh
          name="BookMesh005_3"
          castShadow
          receiveShadow
          geometry={nodes.BookMesh005_3.geometry}
          material={materials.Side_108x175}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/models/Book_XS.gltf");