/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { MaterialProperties } from "three";
import { useLoader } from "@react-three/fiber";

type GLTFResult = GLTF & {
  nodes: {
    BookMesh001: THREE.Mesh;
    BookMesh001_1: THREE.Mesh;
  };
  materials: {
    Front_133x203: THREE.MeshStandardMaterial;
    Pages: THREE.MeshPhysicalMaterial;
  };
};

export function BookMD(
  props: React.JSX.IntrinsicElements["group"] & {
    bookTexture?: string;
    materialControls: Partial<MaterialProperties>;
  }
) {
  const { nodes, materials } = useGLTF(
    "/models/BookMD.glb"
  ) as unknown as GLTFResult;

  const texture = useLoader(
    THREE.TextureLoader,
    props.bookTexture || "/models/textures/template-combined-md.jpg"
  );
  texture.flipY = false;
  texture.colorSpace = THREE.SRGBColorSpace;
  texture.anisotropy = 8;

  const roughnessMap = useLoader(
    THREE.TextureLoader,
    "/models/textures/roughness_map.jpg"
  );

  return (
    <group {...props} dispose={null}>
      <group rotation-y={Math.PI / 2}>
        <mesh
          name="BookMeshMD"
          castShadow
          receiveShadow
          geometry={nodes.BookMesh001.geometry}
        >
          <meshStandardMaterial
            map={texture}
            roughnessMap={roughnessMap}
            toneMapped
            {...props.materialControls}
          />
        </mesh>
        <mesh
          name="BookMesh001_1"
          castShadow
          receiveShadow
          geometry={nodes.BookMesh001_1.geometry}
          material={materials.Pages}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/models/BookMD.glb");
