/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { useBookTextures } from "@/app/hooks/useBookTextures";

type GLTFResult = GLTF & {
  nodes: {
    BookMesh003: THREE.Mesh;
    BookMesh003_1: THREE.Mesh;
    BookMesh003_2: THREE.Mesh;
    BookMesh003_3: THREE.Mesh;
  };
  materials: {
    Front_140x216: THREE.MeshStandardMaterial;
    Pages: THREE.MeshPhysicalMaterial;
    Back_140x216: THREE.MeshStandardMaterial;
    Side_140x216: THREE.MeshStandardMaterial;
  };
};

export function BookLG(
  props: React.JSX.IntrinsicElements["group"] & {
    textures: { front: string; side: string };
  }
) {
  const { nodes, materials } = useGLTF(
    "/models/Book_LG.gltf"
  ) as unknown as GLTFResult;

  // Load and configure textures using the reusable hook
  useBookTextures(props.textures, materials, {
    front: "Front_140x216",
    side: "Side_140x216",
    back: "Back_140x216"
  });

  return (
    <group {...props} dispose={null}>
      <group rotation-y={Math.PI / 2}>
        <mesh
          name="BookMesh003"
          castShadow
          receiveShadow
          geometry={nodes.BookMesh003.geometry}
          material={materials.Front_140x216}
        />
        <mesh
          name="BookMesh003_1"
          castShadow
          receiveShadow
          geometry={nodes.BookMesh003_1.geometry}
          material={materials.Pages}
        />
        <mesh
          name="BookMesh003_2"
          castShadow
          receiveShadow
          geometry={nodes.BookMesh003_2.geometry}
          material={materials.Back_140x216}
        />
        <mesh
          name="BookMesh003_3"
          castShadow
          receiveShadow
          geometry={nodes.BookMesh003_3.geometry}
          material={materials.Side_140x216}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/models/Book_LG.gltf");
