/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useEffect, useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { useFrame, useLoader } from "@react-three/fiber";
import { MeshStandardMaterialProperties } from "three";
import { lerp } from "three/src/math/MathUtils.js";
import { Book } from "@/types/app";
import { bookStore } from "@/app/store/bookStore";
import { useSnapshot } from "valtio";
// import { getContentfulBookSize } from "@/app/utils/book";
// import { useHLSVideoTexture } from "@/app/hooks/useHLSVideoTexture";

type GLTFResult = GLTF & {
  nodes: {
    BookMesh004: THREE.Mesh;
    BookMesh004_1: THREE.Mesh;
  };
  materials: {
    Template_280x260: THREE.MeshStandardMaterial;
    ["Pages.001"]: THREE.MeshPhysicalMaterial;
  };
};

export function Book280x260(
  props: React.JSX.IntrinsicElements["group"] & {
    book: Book;
    materialControls: Partial<MeshStandardMaterialProperties>;
  }
) {
  const { nodes, materials } = useGLTF(
    "/models/Book280x260.glb"
  ) as unknown as GLTFResult;

  const texture = useLoader(
    THREE.TextureLoader,
    props.book?.bookTexture || "/models/textures/template-combined-280x260.jpg"
  );

  // const [width, thickness, height] = useMemo(
  //   () => getContentfulBookSize(props.book.bookSize),
  //   [props.book.bookSize]
  // );

  texture.flipY = false;
  texture.colorSpace = THREE.SRGBColorSpace;
  texture.anisotropy = 8;

  const roughnessMap = useLoader(
    THREE.TextureLoader,
    "/models/textures/roughness_map.jpg"
  );

  // Opacity animation
  const { focusedBookId } = useSnapshot(bookStore);
  const isHidden = focusedBookId !== null && focusedBookId !== props.book.id;
  const ref = useRef<THREE.Group>(null);
  const meshMaterials: THREE.Object3D[] = [];
  const delayFrames = useRef(0);
  const frameCount = useRef(0);

  useEffect(() => {
    frameCount.current = 0;
    delayFrames.current = isHidden ? 25 : 0;
  }, [isHidden]);

  useFrame(() => {
    ref.current?.getObjectsByProperty("type", "Mesh", meshMaterials);
    meshMaterials.forEach((mesh) => {
      const material = (mesh as unknown as THREE.Mesh)
        .material as THREE.MeshStandardMaterial;
      material.transparent = true;
      if (frameCount.current < delayFrames.current) {
        frameCount.current++;
      } else {
        material.opacity = lerp(material.opacity, isHidden ? 0 : 1, 0.5);
      }
    });
    meshMaterials.length = 0;
  });

  // Video configuration
  // const { videoGeometry, videoMaterial, videoPosition, isReady } =
  //   useHLSVideoTexture({
  //     url: "/dog-loop.mp4",
  //     bookWidth: width,
  //     bookHeight: height,
  //     scale: 0.2, // 0 to 1, where 1 fits the video inside the book bounds
  //     coverMode: false, // true for cover mode, false for fit mode
  //     offsetX: 0.9, // -1 to 1, where 0 is centered
  //     offsetY: 0.9, // -1 to 1, where 0 is centered
  //     materialProps: {
  //       roughnessMap: roughnessMap,
  //       ...props.materialControls,
  //     },
  //   });

  return (
    <group {...props} dispose={null}>
      <group rotation-y={Math.PI / 2} ref={ref}>
        <mesh
          name="BookMesh280x260"
          castShadow
          receiveShadow
          geometry={nodes.BookMesh004.geometry}
        >
          <meshStandardMaterial
            map={texture}
            roughnessMap={roughnessMap}
            toneMapped
          />
        </mesh>
        <mesh
          name="BookMesh004_1"
          castShadow
          receiveShadow
          geometry={nodes.BookMesh004_1.geometry}
        >
          <meshStandardMaterial
            {...materials["Pages.001"]}
            {...props.materialControls}
          />
        </mesh>
        {/* {isReady && (
          <mesh
            rotation-x={-Math.PI / 2}
            rotation-z={0}
            position-x={videoPosition.x}
            position-y={thickness / 2}
            position-z={videoPosition.y}
          >
            <circleGeometry args={[videoGeometry.args[0] / 2, 64]} />
            <meshStandardMaterial {...videoMaterial} />
          </mesh>
        )} */}
      </group>
    </group>
  );
}

useGLTF.preload("/models/Book280x260.glb");
